fix: corrected download url and zip filename in installer.sh

diff --git a/codemeta-installer.tmpl b/codemeta-installer.tmpl
--- a/codemeta-installer.tmpl
+++ b/codemeta-installer.tmpl
@@ -22,17 +22,24 @@ case "$$OS_NAME" in
    OS_NAME="macos"
    ;;
 esac
-ZIPFILE="$$PACKAGE-$$VERSION-$$OS_NAME-$$MACHINE.zip"
+ZIPFILE="$$PACKAGE-v$$VERSION-$$OS_NAME-$$MACHINE.zip"
 
 #
 # Check to see if this zip file has been downloaded.
 #
 DOWNLOAD_URL="https://github.com/caltechlibrary/$$PACKAGE/releases/download/v$$VERSION/$$ZIPFILE"
+if ! curl -L -o "$$HOME/Downloads/$$ZIPFILE" "$$DOWNLOAD_URL"; then
+	echo "Curl failed to get $$DOWNLOAD_URL"
+fi
+cat<<EOT
+
+  Retrieved $$DOWNLOAD_URL
+  Saved as $$HOME/Downloads/$$ZIPFILE
+
+EOT
+
 if [ ! -f "$$HOME/Downloads/$$ZIPFILE" ]; then
-	if curl --version > /dev/null 2>&1; then
-		curl -L -o "$$HOME/Downloads/$$ZIPFILE" "$$DOWNLOAD_URL"
-	else
-		cat <<EOT
+	cat<<EOT
 
   To install $$PACKAGE you need to download 
 
@@ -46,25 +53,25 @@ if [ ! -f "$$HOME/Downloads/$$ZIPFILE" ]; then
   that you should be able to re-run $$INSTALLER
 
 EOT
-		exit 1
-	fi
+	exit 1
 fi
 
 START="$$(pwd)"
-mkdir -p $$HOME/.$$PACKAGE/installer
-cd $$HOME/.$$PACKAGE/installer
-unzip $$HOME/Downloads/$$ZIPFILE bin/*
+mkdir -p "$$HOME/.$$PACKAGE/installer"
+cd "$$HOME/.$$PACKAGE/installer" || exit 1
+unzip "$$HOME/Downloads/$$ZIPFILE" "bin/*"
 
 #
 # Copy the application into place
 #
-mkdir -p $$HOME/bin
-EXPLAIN_OS_POLICY="no"
-for APP in $$(find bin -type f); do
-	mv $$APP $$HOME/bin/
-	if ! $$HOME/bin/$$APP >/dev/null 2>%1; then
+mkdir -p "$$HOME/bin"
+EXPLAIN_OS_POLICY="yes"
+find bin -type f | while read -r APP; do
+	V=$$("./$$APP" --version)
+	if [ "$$V" = ""  ]; then 
 		EXPLAIN_OS_POLICY="yes"
 	fi
+	mv "$$APP" "$$HOME/bin/"
 done
 
 #
@@ -72,25 +79,20 @@ done
 #
 DIR_IN_PATH='no'
 for P in $$PATH; do
-  [ "$$p" = "$$HOME/bin" ] && DIR_IN_PATH='yes'
+  if [ "$$P" = "$$HOME/bin" ]; then
+	 DIR_IN_PATH='yes'
+  fi
 done
 if [ "$$DIR_IN_PATH" = "no" ]; then
-	echo 'export PATH="$$HOME/bin:$$PATH"' >>$$HOME/.bashrc
-	echo 'export PATH="$$HOME/bin:$$PATH"' >>$$HOME/.zshrc
+	# shellcheck disable=SC2016
+	echo 'export PATH="$$HOME/bin:$$PATH"' >>"$$HOME/.bashrc"
+	# shellcheck disable=SC2016
+	echo 'export PATH="$$HOME/bin:$$PATH"' >>"$$HOME/.zshrc"
 fi
-rm -fR $$HOME/.$$PACKAGE/installer
-cd $$START
+rm -fR "$$HOME/.$$PACKAGE/installer"
+cd "$$START" || exit 1
 
-if [ "$$OS_NAME" = "macos" ]; then
-	cat <<EOT
-
-If you are running macOS you may need to "right click" on the
-installed files in $$HOME/bin 
-
-and enable them to be 
-EOT
-fi
-
+# shellcheck disable=SC2031
 if [ "$$EXPLAIN_OS_POLICY" = "no" ]; then
 	cat <<EOT
 
